module.exports = (controller) => {
  controller.activeCohorts = ['01', '02']
  controller.materialList = [
    {
      "": "",
      "Day": ":---:",
      "Week": ":----:",
      "Unit": ":----:",
      "Morning Exercise": ":----------------:",
      "Lesson1": ":-------:",
      "Lesson2": ":--------:",
      "Lesson3": ":--------:",
      "Lesson4": ":--------:",
      "Homework1": ":--------:",
      "Homework2": "---------:"
    },
    {
      "": "",
      "Day": 1,
      "Week": 1,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "[orientation](https://git.generalassemb.ly/ga-wdi-boston/orientation)",
      "Lesson2": "[installfest](https://git.generalassemb.ly/ga-wdi-boston/installfest)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[unix-cli-study](https://git.generalassemb.ly/ga-wdi-boston/unix-cli-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 2,
      "Week": 1,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "[unix-cli](https://git.generalassemb.ly/ga-wdi-boston/unix-cli)",
      "Lesson2": "[git](https://git.generalassemb.ly/ga-wdi-boston/git)",
      "Lesson3": "[git-github](https://git.generalassemb.ly/ga-wdi-boston/git-github)",
      "Lesson4": "",
      "Homework1": "[git-practice](https://git.generalassemb.ly/ga-wdi-boston/git-practice)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 3,
      "Week": 1,
      "Unit": 1,
      "Morning Exercise": "[unix-cli-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/unix-cli-diagnostic)",
      "Lesson1": "[js](https://git.generalassemb.ly/ga-wdi-boston/js)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[js-practice](https://git.generalassemb.ly/ga-wdi-boston/js-practice)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 4,
      "Week": 1,
      "Unit": 1,
      "Morning Exercise": "[git-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/git-diagnostic)",
      "Lesson1": "[js-reference-types](https://git.generalassemb.ly/ga-wdi-boston/js-reference-types)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[js-reference-types-practice](https://git.generalassemb.ly/ga-wdi-boston/js-reference-types-practice)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 5,
      "Week": 1,
      "Unit": 1,
      "Morning Exercise": "[js-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/js-diagnostic)",
      "Lesson1": "[js-objects-modeling](https://git.generalassemb.ly/ga-wdi-boston/js-objects-modeling)",
      "Lesson2": "[js-objects-this](https://git.generalassemb.ly/ga-wdi-boston/js-objects-this)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[js-this-prototype-study](https://git.generalassemb.ly/ga-wdi-boston/js-this-prototype-study)",
      "Homework2": "[html-css-study](https://git.generalassemb.ly/ga-wdi-boston/html-css-study)"
    },
    {
      "": "",
      "Day": 6,
      "Week": 2,
      "Unit": 1,
      "Morning Exercise": "[js-reference-types-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/js-reference-types-diagnostic)",
      "Lesson1": "[js-objects-constructors](https://git.generalassemb.ly/ga-wdi-boston/js-objects-constructors)",
      "Lesson2": "[js-objects-prototypes](https://git.generalassemb.ly/ga-wdi-boston/js-objects-prototypes)",
      "Lesson3": "[html-css](https://git.generalassemb.ly/ga-wdi-boston/html-css)",
      "Lesson4": "",
      "Homework1": "[js-functions-study](https://git.generalassemb.ly/ga-wdi-boston/js-Functions-study)",
      "Homework2": "[html-css-layout-study](https://git.generalassemb.ly/ga-wdi-boston/html-css-layout-study)"
    },
    {
      "": "",
      "Day": 7,
      "Week": 2,
      "Unit": 1,
      "Morning Exercise": "[js-objects-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/js-objects-diagnostic)",
      "Lesson1": "[js-functions](https://git.generalassemb.ly/ga-wdi-boston/js-functions)",
      "Lesson2": "[html-css-layout](https://git.generalassemb.ly/ga-wdi-boston/html-css-layout)",
      "Lesson3": "[project-planning-wireframes](https://git.generalassemb.ly/ga-wdi-boston/project-planning-wireframes)",
      "Lesson4": "",
      "Homework1": "[project-planning-wireframes-practice](https://git.generalassemb.ly/ga-wdi-boston/project-planning-wireframes-practice)",
      "Homework2": "[jquery-dom-study](https://git.generalassemb.ly/ga-wdi-boston/jquery-dom-study)"
    },
    {
      "": "",
      "Day": 8,
      "Week": 2,
      "Unit": 1,
      "Morning Exercise": "[js-functions-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/js-functions-diagnostic)",
      "Lesson1": "[js-array-iteration-methods](https://git.generalassemb.ly/ga-wdi-boston/js-array-iteration-methods)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[json-study](https://git.generalassemb.ly/ga-wdi-boston/json-study)",
      "Homework2": "[http-study](https://git.generalassemb.ly/ga-wdi-boston/http-study)"
    },
    {
      "": "",
      "Day": 9,
      "Week": 2,
      "Unit": 1,
      "Morning Exercise": "[html-css-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/html-css-diagnostic)",
      "Lesson1": "[jquery-dom](https://git.generalassemb.ly/ga-wdi-boston/jquery-dom)",
      "Lesson2": "[http-json-discussion](https://git.generalassemb.ly/ga-wdi-boston/http-json-discussion)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[js-async-study](https://git.generalassemb.ly/ga-wdi-boston/http-study)",
      "Homework2": "[library-api-guide](https://git.generalassemb.ly/ga-wdi-boston/library-api-guide)"
    },
    {
      "": "",
      "Day": 10,
      "Week": 2,
      "Unit": 1,
      "Morning Exercise": "[js-array-iteration-methods-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/js-array-iteration-methods-diagnostic)",
      "Lesson1": "[jquery-ajax-crud](https://git.generalassemb.ly/ga-wdi-boston/jquery-ajax-crud)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[spa-study](https://git.generalassemb.ly/ga-wdi-boston/spa-study)",
      "Homework2": "[js-boggle-challenge](https://git.generalassemb.ly/ga-wdi-boston/js-boggle-challenge)"
    },
    {
      "": "",
      "Day": 11,
      "Week": 3,
      "Unit": 1,
      "Morning Exercise": "[jquery-dom-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/jquery-dom-diagnostic)",
      "Lesson1": "[api-token-auth](https://git.generalassemb.ly/ga-wdi-boston/api-token-auth)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[game-project-scope-study](https://git.generalassemb.ly/ga-wdi-boston/game-project-scope-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 12,
      "Week": 3,
      "Unit": 1,
      "Morning Exercise": "[jquery-ajax-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/jquery-ajax-diagnostic)",
      "Lesson1": "[html-css-sass](https://git.generalassemb.ly/ga-wdi-boston/html-css-sass)",
      "Lesson2": "[html-css-layout-bootstrap-sass](https://git.generalassemb.ly/ga-wdi-boston/html-css-layout-bootstrap-sass)",
      "Lesson3": "[game-project-scope-discussion](https://git.generalassemb.ly/ga-wdi-boston/game-project-scope-discussion)",
      "Lesson4": "",
      "Homework1": "[gh-pages-deployment-guide](https://git.generalassemb.ly/ga-wdi-boston/gh-pages-deployment-guide)",
      "Homework2": "[css-layout-challenge](https://git.generalassemb.ly/ga-wdi-boston/css-layout-challenge)"
    },
    {
      "": "",
      "Day": 13,
      "Week": 3,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "Project 1 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 14,
      "Week": 3,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "Project 1 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 15,
      "Week": 3,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "Project 1 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 16,
      "Week": 4,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "Project 1 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 17,
      "Week": 4,
      "Unit": 1,
      "Morning Exercise": "",
      "Lesson1": "Project 1 Presentations",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[ruby-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-study)",
      "Homework2": "[ruby-vs-js-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-vs-js-study)"
    },
    {
      "": "",
      "Day": 18,
      "Week": 4,
      "Unit": 2,
      "Morning Exercise": "[js-euler-palindrome-challenge](https://git.generalassemb.ly/ga-wdi-boston/js-euler-palindrome-challenge)",
      "Lesson1": "[ruby](https://git.generalassemb.ly/ga-wdi-boston/ruby)",
      "Lesson2": "[ruby-arrays](https://git.generalassemb.ly/ga-wdi-boston/ruby-arrays)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[ruby-vs-js-arrays-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-vs-js-arrays-study)",
      "Homework2": "[ruby-vs-js-hash-dictionary-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-vs-js-hash-dictionary-study)"
    },
    {
      "": "",
      "Day": 19,
      "Week": 4,
      "Unit": 2,
      "Morning Exercise": "[ruby-vs-js-list-challenge](https://git.generalassemb.ly/ga-wdi-boston/ruby-vs-js-list-challenge)",
      "Lesson1": "[ruby-hash](https://git.generalassemb.ly/ga-wdi-boston/ruby-hash)",
      "Lesson2": "[ruby-array-methods](https://git.generalassemb.ly/ga-wdi-boston/ruby-array-methods)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[ruby-vs-js-objects-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-vs-js-objects-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 20,
      "Week": 4,
      "Unit": 2,
      "Morning Exercise": "[ruby-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/ruby-diagnostic)",
      "Lesson1": "[ruby-objects](https://git.generalassemb.ly/ga-wdi-boston/ruby-objects)",
      "Lesson2": "[ruby-object-inheritance](https://git.generalassemb.ly/ga-wdi-boston/ruby-object-inheritance)",
      "Lesson3": "[ruby-object-model](https://git.generalassemb.ly/ga-wdi-boston/ruby-object-model)",
      "Lesson4": "",
      "Homework1": "[ruby-gem-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-gem-study)",
      "Homework2": "[ruby-enumerable-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-enumerable-study)"
    },
    {
      "": "",
      "Day": 21,
      "Week": 5,
      "Unit": 2,
      "Morning Exercise": "[ruby-calculator-challenge](https://git.generalassemb.ly/ga-wdi-boston/ruby-calculator-challenge)",
      "Lesson1": "[ruby-object-self](https://git.generalassemb.ly/ga-wdi-boston/ruby-object-self)",
      "Lesson2": "[ruby-object-class-methods](https://git.generalassemb.ly/ga-wdi-boston/ruby-object-class-methods)",
      "Lesson3": "[ruby-enumerable-builtins](https://git.generalassemb.ly/ga-wdi-boston/ruby-enumerable-builtins)",
      "Lesson4": "[ruby-enumerable-comparable](https://git.generalassemb.ly/ga-wdi-boston/ruby-enumerable-comparable)",
      "Homework1": "[rails-activerecord-crud-study](https://git.generalassemb.ly/ga-wdi-boston/rails-activerecord-crud-study)",
      "Homework2": "[sql-study](https://git.generalassemb.ly/ga-wdi-boston/sql-study)"
    },
    {
      "": "",
      "Day": 22,
      "Week": 5,
      "Unit": 2,
      "Morning Exercise": "[ruby-objects-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/ruby-objects-diagnostic)",
      "Lesson1": "[sql](https://git.generalassemb.ly/ga-wdi-boston/sql)",
      "Lesson2": "[rails-api](https://git.generalassemb.ly/ga-wdi-boston/rails-api)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[ruby-objects-practice](https://git.generalassemb.ly/ga-wdi-boston/ruby-objects-practice)",
      "Homework2": "[rails-api-study](https://git.generalassemb.ly/ga-wdi-boston/rails-api-study)"
    },
    {
      "": "",
      "Day": 23,
      "Week": 5,
      "Unit": 2,
      "Morning Exercise": "[ruby-enumerable-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/ruby-enumerable-diagnostic)",
      "Lesson1": "[rails-api-single-resource](https://git.generalassemb.ly/ga-wdi-boston/rails-api-single-resource)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[rails-migrations-study](https://git.generalassemb.ly/ga-wdi-boston/rails-migrations-study)",
      "Homework2": "[rest-study](https://git.generalassemb.ly/ga-wdi-boston/rest-study)"
    },
    {
      "": "",
      "Day": 24,
      "Week": 5,
      "Unit": 2,
      "Morning Exercise": "[sql-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/sql-diagnostic)",
      "Lesson1": "[rails-api-one-to-many](https://git.generalassemb.ly/ga-wdi-boston/rails-api-one-to-many)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[ruby-solid-study](https://git.generalassemb.ly/ga-wdi-boston/ruby-solid-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 25,
      "Week": 5,
      "Unit": 2,
      "Morning Exercise": "[rails-api-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/rails-api-diagnostic)",
      "Lesson1": "[code-retreat](https://git.generalassemb.ly/ga-wdi-boston/code-retreat)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[rails-heroku-setup-guide](https://git.generalassemb.ly/ga-wdi-boston/rails-heroku-setup-guide)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 26,
      "Week": 6,
      "Unit": 2,
      "Morning Exercise": "[rails-api-single-resource-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/rails-api-single-resource-diagnostic)",
      "Lesson1": "[rails-api-many-to-many](https://git.generalassemb.ly/ga-wdi-boston/rails-api-many-to-many)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[full-stack-project-practice](https://git.generalassemb.ly/ga-wdi-boston/full-stack-project-practice)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 27,
      "Week": 6,
      "Unit": 2,
      "Morning Exercise": "[ruby-fibonacci-challenge](https://git.generalassemb.ly/ga-wdi-boston/ruby-fibonacci-challenge)",
      "Lesson1": "[rails-api-bdd](https://git.generalassemb.ly/ga-wdi-boston/rails-api-bdd)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 28,
      "Week": 6,
      "Unit": 2,
      "Morning Exercise": "[rails-api-relationships-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/rails-api-relationships-diagnostic)",
      "Lesson1": "[handlebars](https://git.generalassemb.ly/ga-wdi-boston/handlebars)",
      "Lesson2": "[full-stack-project-modeling-lab](https://git.generalassemb.ly/ga-wdi-boston/full-stack-project-modeling-lab)",
      "Lesson3": "[rails-api-examples-walkthrough](https://git.generalassemb.ly/ga-wdi-boston/rails-api-examples-walkthrough)",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 29,
      "Week": 6,
      "Unit": 2,
      "Morning Exercise": "Project 2 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 30,
      "Week": 6,
      "Unit": 2,
      "Morning Exercise": "Project 2 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 31,
      "Week": 7,
      "Unit": 2,
      "Morning Exercise": "Project 2 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 32,
      "Week": 7,
      "Unit": 2,
      "Morning Exercise": "Project 2 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 33,
      "Week": 7,
      "Unit": 2,
      "Morning Exercise": "Project 2 Presentations",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 34,
      "Week": 7,
      "Unit": 3,
      "Morning Exercise": "",
      "Lesson1": "[git-workflow-teams](https://git.generalassemb.ly/ga-wdi-boston/git-workflow-teams)",
      "Lesson2": "[js-function-context-this](https://git.generalassemb.ly/ga-wdi-boston/js-function-context-this)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[sql-nosql-study](https://git.generalassemb.ly/ga-wdi-boston/sql-nosql-study)",
      "Homework2": "[self-learning-study](https://git.generalassemb.ly/ga-wdi-boston/self-learning-study)"
    },
    {
      "": "",
      "Day": 35,
      "Week": 7,
      "Unit": 3,
      "Morning Exercise": "[js-function-context-this](https://git.generalassemb.ly/ga-wdi-boston/js-function-context-this)",
      "Lesson1": "[node-api](https://git.generalassemb.ly/ga-wdi-boston/node-api)",
      "Lesson2": "[sql-nosql-discussion](https://git.generalassemb.ly/ga-wdi-boston/sql-nosql-discussion)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[mongodb-study](https://git.generalassemb.ly/ga-wdi-boston/mongodb-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 36,
      "Week": 8,
      "Unit": 3,
      "Morning Exercise": "[node-api-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/node-api-diagnostic)",
      "Lesson1": "[node-api-promises](https://git.generalassemb.ly/ga-wdi-boston/node-api-promises)",
      "Lesson2": "[mongodb](https://git.generalassemb.ly/ga-wdi-boston/mongodb)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[js-modules-study](https://git.generalassemb.ly/ga-wdi-boston/js-modules-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 37,
      "Week": 8,
      "Unit": 3,
      "Morning Exercise": "[node-api-promises-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/node-api-promises-diagnostic)",
      "Lesson1": "[mongoose](https://git.generalassemb.ly/ga-wdi-boston/mongoose)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "[node-npm-practice](https://git.generalassemb.ly/ga-wdi-boston/node-npm-practice)",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 38,
      "Week": 8,
      "Unit": 3,
      "Morning Exercise": "[mongodb-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/mongodb-diagnostic)",
      "Lesson1": "[express-api](https://git.generalassemb.ly/ga-wdi-boston/express-api)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[aws-s3-setup-guide](https://git.generalassemb.ly/ga-wdi-boston/aws-s3-setup-guide)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 39,
      "Week": 8,
      "Unit": 3,
      "Morning Exercise": "[mongoose-diagnostic](https://git.generalassemb.ly/ga-wdi-boston/mongoose-diagnostic)",
      "Lesson1": "[express-api](https://git.generalassemb.ly/ga-wdi-boston/express-api)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[express-api-deployment-guide](https://git.generalassemb.ly/ga-wdi-boston/express-api-deployment-guide)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 40,
      "Week": 8,
      "Unit": 3,
      "Morning Exercise": "",
      "Lesson1": "[express-multer](https://git.generalassemb.ly/ga-wdi-boston/express-multer-upload-api)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[cipher-challenge](https://git.generalassemb.ly/ga-wdi-boston/cipher-challenge)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 41,
      "Week": 9,
      "Unit": 3,
      "Morning Exercise": "",
      "Lesson1": "[express-multer](https://git.generalassemb.ly/ga-wdi-boston/express-multer-upload-api)",
      "Lesson2": "[scrum](https://git.generalassemb.ly/ga-wdi-boston/scrum)",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 42,
      "Week": 9,
      "Unit": 3,
      "Morning Exercise": "Project 3 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 43,
      "Week": 9,
      "Unit": 3,
      "Morning Exercise": "Project 3 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 44,
      "Week": 9,
      "Unit": 3,
      "Morning Exercise": "Project 3 Worktime",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 45,
      "Week": 9,
      "Unit": 3,
      "Morning Exercise": "Project 3 Presentations",
      "Lesson1": "",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 46,
      "Week": 10,
      "Unit": 4,
      "Morning Exercise": "[ruby-morse-code-challenge](https://git.generalassemb.ly/ga-wdi-boston/ruby-morse-code-challenge)",
      "Lesson1": "[cs](https://git.generalassemb.ly/ga-wdi-boston/cs)",
      "Lesson2": "[cs-algorithms](https://git.generalassemb.ly/ga-wdi-boston/cs-algorithms)",
      "Lesson3": "[cs-data-structures](https://git.generalassemb.ly/ga-wdi-boston/cs-data-structures)",
      "Lesson4": "",
      "Homework1": "[web-accessability-study](https://git.generalassemb.ly/ga-wdi-boston/web-accessibility-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 47,
      "Week": 10,
      "Unit": 4,
      "Morning Exercise": "[roman-numerals-challenge](https://git.generalassemb.ly/ga-wdi-boston/roman-numerals-challenge)",
      "Lesson1": "[conference](https://git.generalassemb.ly/ga-wdi-boston/conference)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 48,
      "Week": 10,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[conference](https://git.generalassemb.ly/ga-wdi-boston/conference)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 49,
      "Week": 10,
      "Unit": 4,
      "Morning Exercise": "[js-atc-challenge](https://git.generalassemb.ly/ga-wdi-boston/js-atc-challenge)",
      "Lesson1": "[interview-discussion](https://git.generalassemb.ly/ga-wdi-boston/interview-discussion)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[state-machine-challenge](https://git.generalassemb.ly/ga-wdi-boston/state-machine-challenge)",
      "Homework2": "[react-study](https://git.generalassemb.ly/ga-wdi-boston/react-study)"
    },
    {
      "": "",
      "Day": 50,
      "Week": 10,
      "Unit": 4,
      "Morning Exercise": "[js-binary-search-challenge](https://git.generalassemb.ly/ga-wdi-boston/js-binary-search-challenge)",
      "Lesson1": "[react](https://git.generalassemb.ly/ga-wdi-boston/react)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "[react-components-study](https://git.generalassemb.ly/ga-wdi-boston/react-components-study)",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 51,
      "Week": 11,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[react-components-props](https://git.generalassemb.ly/ga-wdi-boston/react-components-and-props)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 52,
      "Week": 11,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[react-components-state](https://git.generalassemb.ly/ga-wdi-boston/react-components-state)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 53,
      "Week": 11,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[react-router](https://git.generalassemb.ly/ga-wdi-boston/react-router)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 54,
      "Week": 11,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[react-crud](https://git.generalassemb.ly/ga-wdi-boston/react-crud)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 55,
      "Week": 11,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "[react-auth](https://git.generalassemb.ly/ga-wdi-boston/react-auth)",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 56,
      "Week": 12,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "Project 4 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 57,
      "Week": 12,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "Project 4 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 58,
      "Week": 12,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "Project 4 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 59,
      "Week": 12,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "Project 4 Worktime",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    },
    {
      "": "",
      "Day": 60,
      "Week": 12,
      "Unit": 4,
      "Morning Exercise": "",
      "Lesson1": "Project 4 Presentations",
      "Lesson2": "",
      "Lesson3": "",
      "Lesson4": "",
      "Homework1": "",
      "Homework2": ""
    }
  ]
}